# Generated by Django 4.1.6 on 2024-01-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0003_alter_student_grad_year_alter_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(default='resumes/default.pdf', upload_to='resumes/'),
        ),
    ]
