# Generated by Django 4.1.6 on 2024-01-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0004_student_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='information',
            field=models.TextField(default='Here is where your bio goes, keep it short, you can edit it by clicking the button in the top right corner...', max_length=600),
        ),
    ]
