# Generated by Django 4.1.6 on 2024-01-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0005_student_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(default='cte/static/cte/resumes/ucdoiowebqicndsup.pdf', upload_to='cte/static/cte/resumes/'),
        ),
    ]
