# Generated by Django 4.1.6 on 2024-02-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0007_business_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='notif_date',
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default='Yours', max_length=100),
            preserve_default=False,
        ),
    ]
