# Generated by Django 4.1.6 on 2024-02-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0008_remove_job_notif_date_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='cte.student'),
        ),
    ]
