# Generated by Django 4.1.6 on 2024-02-14 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0009_job_applicants'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('reason', models.TextField(blank=True, max_length=600)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cte.student')),
            ],
        ),
    ]
