# Generated by Django 4.1.6 on 2024-02-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0011_hoursrequest_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursrequest',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cte.job'),
        ),
    ]
